### ISSUE TITLE
Does not work on Notepad++ v7.5.8 64bit

### ISSUE THREAD

**Issue by RickVR** [naderi/material-theme-for-npp#7]
Settings -> Style Configurator -> Select theme: Material-Dark
Produces the following error: 
Load stylers.xml failed
Load "C:\Apps\Notepad++\themes\Material-Dark.xml" failed!
Tried importing xml file and also dropping it into themes.

**Comment by FrancescoKa** [comment]
Hi, I have had the same problem, but in reality simply downloading the xml file only from git doesn't work because the file downloaded this way is not a valid xml.
You have to :
- download the whole project (or copy just the xml code)
- extract the xml file and copy it in C:\Users\<YourUser>AppData\Roaming\Notepad++\themes\
- restart Notepad and enable the theme

This worked for me with Npp 7.6.2 on Windows 10
